### ISSUE TITLE
Document how to generate instruments

### ISSUE THREAD

**Issue by korakinos** [DLehenbauer/arduino-midi-sound-module#13]
Do you have any documentation about how to generate the instrument code for instruments_generated.h? This could be handy to customize the code with different sound samples, effectively using the programme as a sampler.

PS: This repository is a gem. The documentation in the code comments is super helpful, and I love how the module sounds, especially the subtly staggered decay of sounds and how my keyboard's topmost two octaves come out completely out of tune, prepared-piano style (which could be a bug report, but as I said, I love it). Thank you!

**Comment by DLehenbauer** [comment]
I'm sorry, there is no documentation.  To create the 'instruments_generated.h' file I cobbled together a clunky and unintuitive UI editor.  It's a React web app that uses Emscripten to compile the synthesizer to JavaScript so you can test instruments without having to recompile / deploy to an Arduino.

It's not suitable for release, but I can share the private repo with you if you'd like to try to rejuvenate it.  (It was a super early use of WebAudio before things had completely stabilized, and probably needs some tweaking to get it working again on today's browsers.)

**Comment by korakinos** [comment]
> I'm sorry, there is no documentation. 

That's okay! 

> It's not suitable for release, but I can share the private repo with you if you'd like to try to rejuvenate it.

Since I am not familiar with the tech stack you used (not a single part of it), I would
most probably not try to get your code running, but to understand what it does and write my own version. And I may never get around to that, either. If you are okay with all this, I would be happy to take a look at your repo. If not, then no worries; I can still study the generated Arduino code.

**Comment by DLehenbauer** [comment]
@korakinos - I don't know how helpful it will be, but I'm happy to share.  I've added you as a collaborator to the 'arduino-midi-sound-module-editor' project.  (You may need to accept via an email)

The 'main' branch of the repository is empty.  The code resides in the 'dev' branch:
https://github.com/DLehenbauer/arduino-midi-sound-module-editor/tree/dev

Under the '/src/components' directory are the various UI editors that manipulate data structures under 'model.persistant.synth'.  The instruments and envelope editors are probably the most interesting.

The 'instruments_generate.h' file is produced by serializing these data structures here:
https://github.com/DLehenbauer/arduino-midi-sound-module-editor/blob/dev/src/routes/code/index.js#L120

**Comment by korakinos** [comment]
I got the invitation and will take a look. Thank you for being so forthcoming!
