### ISSUE TITLE
Out of storage space error when compiling

### ISSUE THREAD

**Issue by Yazoo55** [DLehenbauer/arduino-midi-sound-module#3]
I received the following error message when I compiled the project today:

"Sketch uses 32388 bytes (100%) of program storage space. Maximum is 32256 bytes.
Global variables use 1027 bytes (50%) of dynamic memory, leaving 1021 bytes for local variables. Maximum is 2048 bytes."

The Arduino IDE is version 1.8.10 and the target was an Arduino/Genuino Uno. 

For my purposes, I don't need the MIDI Bend facility so I commented this out and it compiled successfully.

**Comment by DLehenbauer** [comment]
Should be fixed in the 'dev' branch (by trimming some unused space from the wavetable.)

**Comment by DLehenbauer** [comment]
Thanks for reporting the issue, @Yazoo55.  Should be fixed in the v0.2 release (now in master).
