### ISSUE TITLE
What is the best way to "Pause" the synth?

### ISSUE THREAD

**Issue by urbantigerau** [DLehenbauer/arduino-midi-sound-module#7]
Hi,

I am building a stand alone midi player based on the midi sound module and the MajicDesigns MD_MIDIFile file player. This is quite well along and it is basically working. I can read files from the SD, display their names on an OLED display, select a file and play it. This has been done by some copying of the the example Command Line Interface rather then by any feat of great genius on my part. 

One of the functions supported by the file player is a pause function. However it does not work well. When paused the synth is not silenced and when restarted it sounds out of synch somehow. Some investigation of commands being sent shows that the problem seems to be linked to the file player. I will raise that with MajicDesigns.

My question relates to the best way to silence the synth on pause so that it can restart. I am not sure if channel command BX 78 0 (all sound off on channel X) works in the synth side and there is also BX 7B 0 (all notes off on channel X) which also looks like a candidate. Maybe there is another better answer? 

I could be wrong but it seems I need to co-ordinate the file player with the synth so that one sends what the other is expecting. So I will start with the synth side and get an understanding and then move to the player side.

Regards, Fred.

**Comment by DLehenbauer** [comment]
The synth supports the 'all notes off' command (0x7B).  Adding support for 'all sounds off' would be a good thing to do, and not at all difficult (see `midiControlChange()` in midisynth.h).

You're welcome to do this and contribute a PR, or if there's no hurry, I'll take care of it the next time I come back to this project.

The MIDI software I use always sends both 'all notes off' and 'all sounds off' on pause, so I never noticed the latter was lacking.  Thanks for letting me know!

**Comment by urbantigerau** [comment]
Thanks for that. I’ll have a look at your code and see how complex it looks. Not too bad from memory, I have already had a look around in there. I won’t commit to developing code, I’ll have to work on the project first. 

Thanks again, great work.

Regards, Fred.

**Comment by urbantigerau** [comment]
Hi Daniel,

My priority first is the file player so I’ll see what comes out of that first.

I’ll have a look at your code and see how complex it looks. Not too bad from memory, I have already had a look around in there. I won’t commit to developing code, I’ll have to work on the project first.

I am have raised a question with the file player side and we will see if I get a response.

Thanks again, great work.

Regards, Fred.

**Comment by DLehenbauer** [comment]
@urbantigerau - Just wanted to let you know that I merged support for 'all sounds off' (0x78) to the master branch (plus a few other tiny tweaks.)
